var annotated_dup =
[
    [ "ai", "de/d58/namespaceai.html", [
      [ "AIServiceFactory", "d9/deb/classai_1_1AIServiceFactory.html", "d9/deb/classai_1_1AIServiceFactory" ],
      [ "AIServiceWrapper", "df/dca/classai_1_1AIServiceWrapper.html", "df/dca/classai_1_1AIServiceWrapper" ],
      [ "AnthropicClient", "dc/d89/classai_1_1AnthropicClient.html", "dc/d89/classai_1_1AnthropicClient" ],
      [ "Config", "db/de8/structai_1_1Config.html", "db/de8/structai_1_1Config" ],
      [ "DirectionPattern", "d5/d23/structai_1_1DirectionPattern.html", "d5/d23/structai_1_1DirectionPattern" ],
      [ "GeminiClient", "d7/d05/classai_1_1GeminiClient.html", "d7/d05/classai_1_1GeminiClient" ],
      [ "GemmaActorResult", "d4/d8f/structai_1_1GemmaActorResult.html", "d4/d8f/structai_1_1GemmaActorResult" ],
      [ "GemmaDirectionResult", "d6/d78/structai_1_1GemmaDirectionResult.html", "d6/d78/structai_1_1GemmaDirectionResult" ],
      [ "GemmaInferenceEngine", "d2/d47/classai_1_1GemmaInferenceEngine.html", "d2/d47/classai_1_1GemmaInferenceEngine" ],
      [ "IAIService", "df/d97/classai_1_1IAIService.html", "df/d97/classai_1_1IAIService" ],
      [ "LLMClient", "d7/d7b/classai_1_1LLMClient.html", "d7/d7b/classai_1_1LLMClient" ],
      [ "LogAnalyzer", "d3/da5/classai_1_1LogAnalyzer.html", "d3/da5/classai_1_1LogAnalyzer" ],
      [ "ModelInfo", "df/db7/structai_1_1ModelInfo.html", "df/db7/structai_1_1ModelInfo" ],
      [ "OllamaClient", "d1/d63/classai_1_1OllamaClient.html", "d1/d63/classai_1_1OllamaClient" ],
      [ "OpenAIClient", "d8/d14/classai_1_1OpenAIClient.html", "d8/d14/classai_1_1OpenAIClient" ]
    ] ],
    [ "analyzer", "dd/d3e/namespaceanalyzer.html", [
      [ "ActorDiscoverer", "d9/d49/classanalyzer_1_1ActorDiscoverer.html", "d9/d49/classanalyzer_1_1ActorDiscoverer" ],
      [ "ActorDiscoveryResult", "d8/d24/structanalyzer_1_1ActorDiscoveryResult.html", "d8/d24/structanalyzer_1_1ActorDiscoveryResult" ],
      [ "ExchangePattern", "d8/d76/structanalyzer_1_1ExchangePattern.html", "d8/d76/structanalyzer_1_1ExchangePattern" ]
    ] ],
    [ "config", "d6/d7f/namespaceconfig.html", [
      [ "ColumnColor", "da/dc9/structconfig_1_1ColumnColor.html", "da/dc9/structconfig_1_1ColumnColor" ],
      [ "ColumnConfig", "db/deb/structconfig_1_1ColumnConfig.html", "db/deb/structconfig_1_1ColumnConfig" ],
      [ "Config", "d2/d5e/classconfig_1_1Config.html", "d2/d5e/classconfig_1_1Config" ],
      [ "ConfigObserver", "d0/d90/classconfig_1_1ConfigObserver.html", "d0/d90/classconfig_1_1ConfigObserver" ],
      [ "FieldConversionPluginRegistry", "d7/d29/classconfig_1_1FieldConversionPluginRegistry.html", "d7/d29/classconfig_1_1FieldConversionPluginRegistry" ],
      [ "FieldDictionary", "d1/de4/structconfig_1_1FieldDictionary.html", "d1/de4/structconfig_1_1FieldDictionary" ],
      [ "FieldTranslator", "d9/da7/classconfig_1_1FieldTranslator.html", "d9/da7/classconfig_1_1FieldTranslator" ],
      [ "HexToAsciiPlugin", "d3/de9/classconfig_1_1HexToAsciiPlugin.html", "d3/de9/classconfig_1_1HexToAsciiPlugin" ],
      [ "IsoLatinPlugin", "d9/df3/classconfig_1_1IsoLatinPlugin.html", "d9/df3/classconfig_1_1IsoLatinPlugin" ],
      [ "ItemHighlight", "de/d64/structconfig_1_1ItemHighlight.html", "de/d64/structconfig_1_1ItemHighlight" ],
      [ "NidEnginePlugin", "d9/d37/classconfig_1_1NidEnginePlugin.html", "d9/d37/classconfig_1_1NidEnginePlugin" ],
      [ "NidLrbgPlugin", "d3/dfb/classconfig_1_1NidLrbgPlugin.html", "d3/dfb/classconfig_1_1NidLrbgPlugin" ],
      [ "TCyclocPlugin", "d8/de9/classconfig_1_1TCyclocPlugin.html", "d8/de9/classconfig_1_1TCyclocPlugin" ],
      [ "TrackConditionPlugin", "d4/d6b/classconfig_1_1TrackConditionPlugin.html", "d4/d6b/classconfig_1_1TrackConditionPlugin" ],
      [ "TranslationResult", "dd/d7c/structconfig_1_1TranslationResult.html", "dd/d7c/structconfig_1_1TranslationResult" ],
      [ "UnixToDatePlugin", "df/dac/classconfig_1_1UnixToDatePlugin.html", "df/dac/classconfig_1_1UnixToDatePlugin" ],
      [ "ValueMapPlugin", "d2/d8e/classconfig_1_1ValueMapPlugin.html", "d2/d8e/classconfig_1_1ValueMapPlugin" ]
    ] ],
    [ "db", "d0/d45/namespacedb.html", [
      [ "EventsContainer", "dd/dc2/classdb_1_1EventsContainer.html", "dd/dc2/classdb_1_1EventsContainer" ],
      [ "LogEvent", "d1/d00/classdb_1_1LogEvent.html", "d1/d00/classdb_1_1LogEvent" ]
    ] ],
    [ "error", "da/d7e/namespaceerror.html", [
      [ "Error", "d7/d0d/classerror_1_1Error.html", "d7/d0d/classerror_1_1Error" ]
    ] ],
    [ "filters", "d8/d6b/namespacefilters.html", [
      [ "ExactMatchStrategy", "de/d0e/classfilters_1_1ExactMatchStrategy.html", "de/d0e/classfilters_1_1ExactMatchStrategy" ],
      [ "Filter", "d9/d12/classfilters_1_1Filter.html", "d9/d12/classfilters_1_1Filter" ],
      [ "FilterCondition", "dc/d53/structfilters_1_1FilterCondition.html", "dc/d53/structfilters_1_1FilterCondition" ],
      [ "FilterManager", "d5/db4/classfilters_1_1FilterManager.html", "d5/db4/classfilters_1_1FilterManager" ],
      [ "FilterOptimizer", "d9/dd7/classfilters_1_1FilterOptimizer.html", "d9/dd7/classfilters_1_1FilterOptimizer" ],
      [ "FilterSerializer", "d5/d8f/classfilters_1_1FilterSerializer.html", "d5/d8f/classfilters_1_1FilterSerializer" ],
      [ "FuzzyMatchStrategy", "d7/db2/classfilters_1_1FuzzyMatchStrategy.html", "d7/db2/classfilters_1_1FuzzyMatchStrategy" ],
      [ "IFilterStrategy", "df/d7b/classfilters_1_1IFilterStrategy.html", "df/d7b/classfilters_1_1IFilterStrategy" ],
      [ "RegexFilterStrategy", "d0/dd5/classfilters_1_1RegexFilterStrategy.html", "d0/dd5/classfilters_1_1RegexFilterStrategy" ],
      [ "WildcardStrategy", "d4/d6e/classfilters_1_1WildcardStrategy.html", "d4/d6e/classfilters_1_1WildcardStrategy" ]
    ] ],
    [ "mvc", "da/ddc/namespacemvc.html", [
      [ "IController", "d1/d06/classmvc_1_1IController.html", "d1/d06/classmvc_1_1IController" ],
      [ "IModel", "dc/d2d/classmvc_1_1IModel.html", "dc/d2d/classmvc_1_1IModel" ],
      [ "IModelObservable", "da/d80/classmvc_1_1IModelObservable.html", "da/d80/classmvc_1_1IModelObservable" ],
      [ "IView", "d3/dba/classmvc_1_1IView.html", "d3/dba/classmvc_1_1IView" ],
      [ "MainController", "d5/d44/classmvc_1_1MainController.html", "d5/d44/classmvc_1_1MainController" ],
      [ "SearchResultRow", "de/d74/structmvc_1_1SearchResultRow.html", "de/d74/structmvc_1_1SearchResultRow" ]
    ] ],
    [ "parser", "d0/dd5/namespaceparser.html", [
      [ "dbc", "d8/d04/namespaceparser_1_1dbc.html", [
        [ "DbcDatabase", "d1/db6/structparser_1_1dbc_1_1DbcDatabase.html", "d1/db6/structparser_1_1dbc_1_1DbcDatabase" ],
        [ "DbcMessage", "d9/d4f/structparser_1_1dbc_1_1DbcMessage.html", "d9/d4f/structparser_1_1dbc_1_1DbcMessage" ],
        [ "DbcSignal", "d3/dc2/structparser_1_1dbc_1_1DbcSignal.html", "d3/dc2/structparser_1_1dbc_1_1DbcSignal" ]
      ] ],
      [ "AscParser", "dd/dfa/classparser_1_1AscParser.html", "dd/dfa/classparser_1_1AscParser" ],
      [ "CsvParser", "d9/dd2/classparser_1_1CsvParser.html", "d9/dd2/classparser_1_1CsvParser" ],
      [ "DltParser", "db/de9/classparser_1_1DltParser.html", "db/de9/classparser_1_1DltParser" ],
      [ "EvlogParser", "d1/d55/classparser_1_1EvlogParser.html", "d1/d55/classparser_1_1EvlogParser" ],
      [ "EvlogTemplate", "dc/d0f/structparser_1_1EvlogTemplate.html", "dc/d0f/structparser_1_1EvlogTemplate" ],
      [ "EvlogTemplateField", "d5/dcd/structparser_1_1EvlogTemplateField.html", "d5/dcd/structparser_1_1EvlogTemplateField" ],
      [ "EvlogTemplateRegistry", "d7/d64/classparser_1_1EvlogTemplateRegistry.html", "d7/d64/classparser_1_1EvlogTemplateRegistry" ],
      [ "IDataParser", "d3/d8b/classparser_1_1IDataParser.html", "d3/d8b/classparser_1_1IDataParser" ],
      [ "IDataParserObserver", "df/d79/classparser_1_1IDataParserObserver.html", "df/d79/classparser_1_1IDataParserObserver" ],
      [ "JsonParser", "d1/d10/classparser_1_1JsonParser.html", "d1/d10/classparser_1_1JsonParser" ],
      [ "ParserFactory", "dc/d03/classparser_1_1ParserFactory.html", "dc/d03/classparser_1_1ParserFactory" ],
      [ "ParserState", "de/d53/structparser_1_1ParserState.html", "de/d53/structparser_1_1ParserState" ],
      [ "XmlParser", "db/d5c/classparser_1_1XmlParser.html", "db/d5c/classparser_1_1XmlParser" ]
    ] ],
    [ "plugin", "d3/d7e/namespaceplugin.html", [
      [ "anonymous_namespace{PluginManager.cpp}", "d8/d08/namespaceplugin_1_1anonymous__namespace_02PluginManager_8cpp_03.html", [
        [ "VersionParts", "df/d14/structplugin_1_1anonymous__namespace_02PluginManager_8cpp_03_1_1VersionParts.html", "df/d14/structplugin_1_1anonymous__namespace_02PluginManager_8cpp_03_1_1VersionParts" ]
      ] ],
      [ "AIProviderPlugin", "d5/d83/classplugin_1_1AIProviderPlugin.html", "d5/d83/classplugin_1_1AIProviderPlugin" ],
      [ "FunctionRegistry", "d9/d75/classplugin_1_1FunctionRegistry.html", "d9/d75/classplugin_1_1FunctionRegistry" ],
      [ "IFieldConversionPlugin", "d8/d3a/classplugin_1_1IFieldConversionPlugin.html", "d8/d3a/classplugin_1_1IFieldConversionPlugin" ],
      [ "IPlugin", "d4/d51/classplugin_1_1IPlugin.html", "d4/d51/classplugin_1_1IPlugin" ],
      [ "IPluginEventObserver", "d1/d7b/classplugin_1_1IPluginEventObserver.html", "d1/d7b/classplugin_1_1IPluginEventObserver" ],
      [ "IPluginObserver", "da/d7b/classplugin_1_1IPluginObserver.html", "da/d7b/classplugin_1_1IPluginObserver" ],
      [ "PluginDependencyGraph", "df/d48/classplugin_1_1PluginDependencyGraph.html", "df/d48/classplugin_1_1PluginDependencyGraph" ],
      [ "PluginEvent", "de/d7a/structplugin_1_1PluginEvent.html", "de/d7a/structplugin_1_1PluginEvent" ],
      [ "PluginEventBus", "da/d30/classplugin_1_1PluginEventBus.html", "da/d30/classplugin_1_1PluginEventBus" ],
      [ "PluginLoadInfo", "d4/dfa/structplugin_1_1PluginLoadInfo.html", "d4/dfa/structplugin_1_1PluginLoadInfo" ],
      [ "PluginManager", "d3/d67/classplugin_1_1PluginManager.html", "d3/d67/classplugin_1_1PluginManager" ],
      [ "PluginMetadata", "de/d25/structplugin_1_1PluginMetadata.html", "de/d25/structplugin_1_1PluginMetadata" ]
    ] ],
    [ "services", "db/d91/namespaceservices.html", [
      [ "IService", "d2/d99/classservices_1_1IService.html", "d2/d99/classservices_1_1IService" ]
    ] ],
    [ "ui", "d3/df6/namespaceui.html", [
      [ "qt", "d6/d40/namespaceui_1_1qt.html", [
        [ "anonymous_namespace{ActorsPanel.cpp}", "d1/dae/namespaceui_1_1qt_1_1anonymous__namespace_02ActorsPanel_8cpp_03.html", [
          [ "ActorTreeItem", "d8/dc2/classui_1_1qt_1_1anonymous__namespace_02ActorsPanel_8cpp_03_1_1ActorTreeItem.html", "d8/dc2/classui_1_1qt_1_1anonymous__namespace_02ActorsPanel_8cpp_03_1_1ActorTreeItem" ]
        ] ],
        [ "anonymous_namespace{CanStatisticsStrategy.cpp}", "d9/d9d/namespaceui_1_1qt_1_1anonymous__namespace_02CanStatisticsStrategy_8cpp_03.html", [
          [ "Accum", "d4/d33/structui_1_1qt_1_1anonymous__namespace_02CanStatisticsStrategy_8cpp_03_1_1Accum.html", "d4/d33/structui_1_1qt_1_1anonymous__namespace_02CanStatisticsStrategy_8cpp_03_1_1Accum" ]
        ] ],
        [ "anonymous_namespace{TraceViewerPanel.cpp}", "da/dee/namespaceui_1_1qt_1_1anonymous__namespace_02TraceViewerPanel_8cpp_03.html", [
          [ "TraceTreeItem", "d2/dc6/classui_1_1qt_1_1anonymous__namespace_02TraceViewerPanel_8cpp_03_1_1TraceTreeItem.html", "d2/dc6/classui_1_1qt_1_1anonymous__namespace_02TraceViewerPanel_8cpp_03_1_1TraceTreeItem" ]
        ] ],
        [ "utils", "dd/d73/namespaceui_1_1qt_1_1utils.html", [
          [ "EventGroupManager", "dd/d37/classui_1_1qt_1_1utils_1_1EventGroupManager.html", "dd/d37/classui_1_1qt_1_1utils_1_1EventGroupManager" ],
          [ "EventTagManager", "da/d36/classui_1_1qt_1_1utils_1_1EventTagManager.html", "da/d36/classui_1_1qt_1_1utils_1_1EventTagManager" ],
          [ "KeyboardNavigationManager", "dd/ddc/classui_1_1qt_1_1utils_1_1KeyboardNavigationManager.html", "dd/ddc/classui_1_1qt_1_1utils_1_1KeyboardNavigationManager" ],
          [ "NotificationManager", "d4/df3/classui_1_1qt_1_1utils_1_1NotificationManager.html", "d4/df3/classui_1_1qt_1_1utils_1_1NotificationManager" ],
          [ "ReportGenerator", "d3/dbb/classui_1_1qt_1_1utils_1_1ReportGenerator.html", "d3/dbb/classui_1_1qt_1_1utils_1_1ReportGenerator" ],
          [ "SearchEngine", "d6/da4/classui_1_1qt_1_1utils_1_1SearchEngine.html", "d6/da4/classui_1_1qt_1_1utils_1_1SearchEngine" ],
          [ "SearchMatch", "db/d1c/structui_1_1qt_1_1utils_1_1SearchMatch.html", "db/d1c/structui_1_1qt_1_1utils_1_1SearchMatch" ],
          [ "SessionManager", "d5/da1/classui_1_1qt_1_1utils_1_1SessionManager.html", "d5/da1/classui_1_1qt_1_1utils_1_1SessionManager" ],
          [ "ThemeManager", "d0/db0/classui_1_1qt_1_1utils_1_1ThemeManager.html", "d0/db0/classui_1_1qt_1_1utils_1_1ThemeManager" ]
        ] ],
        [ "widgets", "d0/d00/namespaceui_1_1qt_1_1widgets.html", [
          [ "PanelInfo", "d2/ddb/structui_1_1qt_1_1widgets_1_1PanelInfo.html", "d2/ddb/structui_1_1qt_1_1widgets_1_1PanelInfo" ],
          [ "PanelNavigator", "d9/da2/classui_1_1qt_1_1widgets_1_1PanelNavigator.html", "d9/da2/classui_1_1qt_1_1widgets_1_1PanelNavigator" ]
        ] ],
        [ "ActorDefinition", "de/db8/structui_1_1qt_1_1ActorDefinition.html", "de/db8/structui_1_1qt_1_1ActorDefinition" ],
        [ "ActorDefinitionsPanel", "dc/ddc/classui_1_1qt_1_1ActorDefinitionsPanel.html", "dc/ddc/classui_1_1qt_1_1ActorDefinitionsPanel" ],
        [ "ActorKey", "d4/d72/structui_1_1qt_1_1ActorKey.html", "d4/d72/structui_1_1qt_1_1ActorKey" ],
        [ "ActorsPanel", "d2/d40/classui_1_1qt_1_1ActorsPanel.html", "d2/d40/classui_1_1qt_1_1ActorsPanel" ],
        [ "AIAnalysisPanel", "d9/dad/classui_1_1qt_1_1AIAnalysisPanel.html", "d9/dad/classui_1_1qt_1_1AIAnalysisPanel" ],
        [ "AIChatPanel", "d6/d8a/classui_1_1qt_1_1AIChatPanel.html", "d6/d8a/classui_1_1qt_1_1AIChatPanel" ],
        [ "AIConfigPanel", "d8/d24/classui_1_1qt_1_1AIConfigPanel.html", "d8/d24/classui_1_1qt_1_1AIConfigPanel" ],
        [ "AIPreferencesPanel", "d4/d8b/classui_1_1qt_1_1AIPreferencesPanel.html", "d4/d8b/classui_1_1qt_1_1AIPreferencesPanel" ],
        [ "BookmarksPanel", "d0/d5d/classui_1_1qt_1_1BookmarksPanel.html", "d0/d5d/classui_1_1qt_1_1BookmarksPanel" ],
        [ "CanSignalTreePanel", "d8/d9e/classui_1_1qt_1_1CanSignalTreePanel.html", "d8/d9e/classui_1_1qt_1_1CanSignalTreePanel" ],
        [ "CanStatisticsStrategy", "dc/de5/classui_1_1qt_1_1CanStatisticsStrategy.html", "dc/de5/classui_1_1qt_1_1CanStatisticsStrategy" ],
        [ "ConfigEditorDialog", "d5/db0/classui_1_1qt_1_1ConfigEditorDialog.html", "d5/db0/classui_1_1qt_1_1ConfigEditorDialog" ],
        [ "DashboardPanel", "d2/d8a/classui_1_1qt_1_1DashboardPanel.html", "d2/d8a/classui_1_1qt_1_1DashboardPanel" ],
        [ "DisplayPreferencesPanel", "dc/d61/classui_1_1qt_1_1DisplayPreferencesPanel.html", "dc/d61/classui_1_1qt_1_1DisplayPreferencesPanel" ],
        [ "EventsTableModel", "d4/d7a/classui_1_1qt_1_1EventsTableModel.html", "d4/d7a/classui_1_1qt_1_1EventsTableModel" ],
        [ "EventsTableView", "d6/d26/classui_1_1qt_1_1EventsTableView.html", "d6/d26/classui_1_1qt_1_1EventsTableView" ],
        [ "ExportDialog", "d3/de3/classui_1_1qt_1_1ExportDialog.html", "d3/de3/classui_1_1qt_1_1ExportDialog" ],
        [ "FileTailer", "d6/d80/classui_1_1qt_1_1FileTailer.html", "d6/d80/classui_1_1qt_1_1FileTailer" ],
        [ "FilterEditorDialog", "dd/d5e/classui_1_1qt_1_1FilterEditorDialog.html", "dd/d5e/classui_1_1qt_1_1FilterEditorDialog" ],
        [ "FilterProfile", "db/d6d/structui_1_1qt_1_1FilterProfile.html", "db/d6d/structui_1_1qt_1_1FilterProfile" ],
        [ "FilterProfilesPanel", "da/d47/classui_1_1qt_1_1FilterProfilesPanel.html", "da/d47/classui_1_1qt_1_1FilterProfilesPanel" ],
        [ "FiltersPanel", "d8/db0/classui_1_1qt_1_1FiltersPanel.html", "d8/db0/classui_1_1qt_1_1FiltersPanel" ],
        [ "FilterStatusBar", "d7/ddd/classui_1_1qt_1_1FilterStatusBar.html", "d7/ddd/classui_1_1qt_1_1FilterStatusBar" ],
        [ "FrameSignals", "da/d91/structui_1_1qt_1_1FrameSignals.html", "da/d91/structui_1_1qt_1_1FrameSignals" ],
        [ "GemmaDownloadDialog", "df/de6/classui_1_1qt_1_1GemmaDownloadDialog.html", "df/de6/classui_1_1qt_1_1GemmaDownloadDialog" ],
        [ "GeneralPreferencesPanel", "d9/dee/classui_1_1qt_1_1GeneralPreferencesPanel.html", "d9/dee/classui_1_1qt_1_1GeneralPreferencesPanel" ],
        [ "GenericStatisticsStrategy", "d9/de8/classui_1_1qt_1_1GenericStatisticsStrategy.html", "d9/de8/classui_1_1qt_1_1GenericStatisticsStrategy" ],
        [ "IStatisticsStrategy", "df/dae/classui_1_1qt_1_1IStatisticsStrategy.html", "df/dae/classui_1_1qt_1_1IStatisticsStrategy" ],
        [ "ItemDetailsView", "d0/d5c/classui_1_1qt_1_1ItemDetailsView.html", "d0/d5c/classui_1_1qt_1_1ItemDetailsView" ],
        [ "LayoutDescriptor", "de/d5a/structui_1_1qt_1_1LayoutDescriptor.html", "de/d5a/structui_1_1qt_1_1LayoutDescriptor" ],
        [ "LayoutManager", "d8/d9f/classui_1_1qt_1_1LayoutManager.html", "d8/d9f/classui_1_1qt_1_1LayoutManager" ],
        [ "LogFileLoadDialog", "d2/d11/classui_1_1qt_1_1LogFileLoadDialog.html", "d2/d11/classui_1_1qt_1_1LogFileLoadDialog" ],
        [ "MainWindow", "d4/dfa/classui_1_1qt_1_1MainWindow.html", "d4/dfa/classui_1_1qt_1_1MainWindow" ],
        [ "MainWindowExportOpsHelper", "da/d0e/classui_1_1qt_1_1MainWindowExportOpsHelper.html", "da/d0e/classui_1_1qt_1_1MainWindowExportOpsHelper" ],
        [ "MainWindowFileOpsHelper", "da/d39/classui_1_1qt_1_1MainWindowFileOpsHelper.html", "da/d39/classui_1_1qt_1_1MainWindowFileOpsHelper" ],
        [ "MainWindowFilterOpsHelper", "d3/d3b/classui_1_1qt_1_1MainWindowFilterOpsHelper.html", "d3/d3b/classui_1_1qt_1_1MainWindowFilterOpsHelper" ],
        [ "MainWindowPluginOpsHelper", "d1/d98/classui_1_1qt_1_1MainWindowPluginOpsHelper.html", "d1/d98/classui_1_1qt_1_1MainWindowPluginOpsHelper" ],
        [ "OllamaSetupDialog", "db/dd2/classui_1_1qt_1_1OllamaSetupDialog.html", "db/dd2/classui_1_1qt_1_1OllamaSetupDialog" ],
        [ "PatternAnalysisPanel", "dd/db3/classui_1_1qt_1_1PatternAnalysisPanel.html", "dd/db3/classui_1_1qt_1_1PatternAnalysisPanel" ],
        [ "PerformancePreferencesPanel", "dd/d69/classui_1_1qt_1_1PerformancePreferencesPanel.html", "dd/d69/classui_1_1qt_1_1PerformancePreferencesPanel" ],
        [ "PluginManagerDialog", "da/d9c/classui_1_1qt_1_1PluginManagerDialog.html", "da/d9c/classui_1_1qt_1_1PluginManagerDialog" ],
        [ "PluginsPreferencesPanel", "d8/daf/classui_1_1qt_1_1PluginsPreferencesPanel.html", "d8/daf/classui_1_1qt_1_1PluginsPreferencesPanel" ],
        [ "PreferencesDialog", "dd/ddf/classui_1_1qt_1_1PreferencesDialog.html", "dd/ddf/classui_1_1qt_1_1PreferencesDialog" ],
        [ "ScenariosPanel", "dc/dff/classui_1_1qt_1_1ScenariosPanel.html", "dc/dff/classui_1_1qt_1_1ScenariosPanel" ],
        [ "SearchBar", "dd/d79/classui_1_1qt_1_1SearchBar.html", "dd/d79/classui_1_1qt_1_1SearchBar" ],
        [ "SearchResultsView", "d9/dfd/classui_1_1qt_1_1SearchResultsView.html", "d9/dfd/classui_1_1qt_1_1SearchResultsView" ],
        [ "SequenceDiagramPanel", "d0/d36/classui_1_1qt_1_1SequenceDiagramPanel.html", "d0/d36/classui_1_1qt_1_1SequenceDiagramPanel" ],
        [ "ShortcutInfo", "d3/da1/structui_1_1qt_1_1ShortcutInfo.html", "d3/da1/structui_1_1qt_1_1ShortcutInfo" ],
        [ "ShortcutManager", "db/d66/classui_1_1qt_1_1ShortcutManager.html", "db/d66/classui_1_1qt_1_1ShortcutManager" ],
        [ "ShortcutsDialog", "d2/d1f/classui_1_1qt_1_1ShortcutsDialog.html", "d2/d1f/classui_1_1qt_1_1ShortcutsDialog" ],
        [ "SideBySidePanel", "df/dbf/classui_1_1qt_1_1SideBySidePanel.html", "df/dbf/classui_1_1qt_1_1SideBySidePanel" ],
        [ "SignalPlotPanel", "d5/d5c/classui_1_1qt_1_1SignalPlotPanel.html", "d5/d5c/classui_1_1qt_1_1SignalPlotPanel" ],
        [ "StartupSplash", "d7/dda/classui_1_1qt_1_1StartupSplash.html", "d7/dda/classui_1_1qt_1_1StartupSplash" ],
        [ "StatRow", "d9/d3b/structui_1_1qt_1_1StatRow.html", "d9/d3b/structui_1_1qt_1_1StatRow" ],
        [ "StatsSection", "d2/d71/structui_1_1qt_1_1StatsSection.html", "d2/d71/structui_1_1qt_1_1StatsSection" ],
        [ "StatsSummaryPanel", "d6/da4/classui_1_1qt_1_1StatsSummaryPanel.html", "d6/da4/classui_1_1qt_1_1StatsSummaryPanel" ],
        [ "StructuredConfigDialog", "d7/dcb/classui_1_1qt_1_1StructuredConfigDialog.html", "d7/dcb/classui_1_1qt_1_1StructuredConfigDialog" ],
        [ "TabBadgeManager", "d8/dab/classui_1_1qt_1_1TabBadgeManager.html", "d8/dab/classui_1_1qt_1_1TabBadgeManager" ],
        [ "ThemeCustomizationDialog", "d4/d52/classui_1_1qt_1_1ThemeCustomizationDialog.html", "d4/d52/classui_1_1qt_1_1ThemeCustomizationDialog" ],
        [ "TimelineChartPanel", "d1/dc4/classui_1_1qt_1_1TimelineChartPanel.html", "d1/dc4/classui_1_1qt_1_1TimelineChartPanel" ],
        [ "TimeRangeFilterPanel", "d1/d76/classui_1_1qt_1_1TimeRangeFilterPanel.html", "d1/d76/classui_1_1qt_1_1TimeRangeFilterPanel" ],
        [ "TraceViewerPanel", "dc/dd0/classui_1_1qt_1_1TraceViewerPanel.html", "dc/dd0/classui_1_1qt_1_1TraceViewerPanel" ],
        [ "TypeFilterView", "d3/df9/classui_1_1qt_1_1TypeFilterView.html", "d3/df9/classui_1_1qt_1_1TypeFilterView" ],
        [ "UnifiedSearchBar", "d4/da3/classui_1_1qt_1_1UnifiedSearchBar.html", "d4/da3/classui_1_1qt_1_1UnifiedSearchBar" ],
        [ "UpdateChecker", "de/d35/classui_1_1qt_1_1UpdateChecker.html", "de/d35/classui_1_1qt_1_1UpdateChecker" ],
        [ "UpdateDialog", "d5/d32/classui_1_1qt_1_1UpdateDialog.html", "d5/d32/classui_1_1qt_1_1UpdateDialog" ]
      ] ],
      [ "IErrorPresenter", "d0/d7f/classui_1_1IErrorPresenter.html", "d0/d7f/classui_1_1IErrorPresenter" ],
      [ "IEventDetailsView", "d9/df7/classui_1_1IEventDetailsView.html", "d9/df7/classui_1_1IEventDetailsView" ],
      [ "IEventsListView", "d6/d4a/classui_1_1IEventsListView.html", "d6/d4a/classui_1_1IEventsListView" ],
      [ "IItemDetailsView", "dc/d5e/classui_1_1IItemDetailsView.html", "dc/d5e/classui_1_1IItemDetailsView" ],
      [ "IMainWindowView", "d3/d1f/classui_1_1IMainWindowView.html", "d3/d1f/classui_1_1IMainWindowView" ],
      [ "ISearchResultsView", "dc/d38/classui_1_1ISearchResultsView.html", "dc/d38/classui_1_1ISearchResultsView" ],
      [ "ISearchResultsViewObserver", "d3/df7/classui_1_1ISearchResultsViewObserver.html", "d3/df7/classui_1_1ISearchResultsViewObserver" ],
      [ "ITypeFilterView", "df/d7e/classui_1_1ITypeFilterView.html", "df/d7e/classui_1_1ITypeFilterView" ],
      [ "MainWindowPresenter", "d5/dc9/classui_1_1MainWindowPresenter.html", "d5/dc9/classui_1_1MainWindowPresenter" ],
      [ "NoopErrorPresenter", "d4/d5b/classui_1_1NoopErrorPresenter.html", "d4/d5b/classui_1_1NoopErrorPresenter" ],
      [ "UiServices", "da/dab/classui_1_1UiServices.html", "da/dab/classui_1_1UiServices" ]
    ] ],
    [ "updates", "d5/d16/namespaceupdates.html", [
      [ "AppUpdateInfo", "d5/d29/structupdates_1_1AppUpdateInfo.html", "d5/d29/structupdates_1_1AppUpdateInfo" ],
      [ "PluginUpdateInfo", "db/da4/structupdates_1_1PluginUpdateInfo.html", "db/da4/structupdates_1_1PluginUpdateInfo" ],
      [ "UpdateCheckResult", "dd/d5c/structupdates_1_1UpdateCheckResult.html", "dd/d5c/structupdates_1_1UpdateCheckResult" ]
    ] ],
    [ "util", "d6/d72/namespaceutil.html", [
      [ "ILogger", "d3/dc4/classutil_1_1ILogger.html", "d3/dc4/classutil_1_1ILogger" ],
      [ "KeyEncryption", "dc/d46/classutil_1_1KeyEncryption.html", "dc/d46/classutil_1_1KeyEncryption" ],
      [ "Logger", "d2/d44/classutil_1_1Logger.html", "d2/d44/classutil_1_1Logger" ],
      [ "Result", "dd/d2d/classutil_1_1Result.html", "dd/d2d/classutil_1_1Result" ],
      [ "Result< void, E >", "d2/de6/classutil_1_1Result_3_01void_00_01E_01_4.html", "d2/de6/classutil_1_1Result_3_01void_00_01E_01_4" ],
      [ "SpdLogger", "dd/d6b/classutil_1_1SpdLogger.html", "dd/d6b/classutil_1_1SpdLogger" ]
    ] ],
    [ "Version", "d8/d16/namespaceVersion.html", [
      [ "Version", "d1/d14/structVersion_1_1Version.html", "d1/d14/structVersion_1_1Version" ]
    ] ],
    [ "ArrowItem", "df/d2a/classArrowItem.html", "df/d2a/classArrowItem" ],
    [ "ClickScene", "d5/ddf/classClickScene.html", "d5/ddf/classClickScene" ],
    [ "QAbstractTableModel", "d7/d33/classQAbstractTableModel.html", null ],
    [ "QDialog", "d9/d46/classQDialog.html", null ],
    [ "QGraphicsLineItem", "d6/d1f/classQGraphicsLineItem.html", null ],
    [ "QGraphicsScene", "d9/d74/classQGraphicsScene.html", null ],
    [ "QMainWindow", "df/d90/classQMainWindow.html", null ],
    [ "QObject", "d9/d5b/classQObject.html", null ],
    [ "QTableView", "d8/d5e/classQTableView.html", null ],
    [ "QTreeWidget", "d3/d5f/classQTreeWidget.html", null ],
    [ "QTreeWidgetItem", "d1/d15/classQTreeWidgetItem.html", null ],
    [ "QWidget", "d8/ded/classQWidget.html", null ],
    [ "Version", "d4/d46/structVersion.html", null ]
];