var dir_92253e525a76926df002d8cd8cf7d558 =
[
    [ "AIAnalysisPanel.cpp", "d4/deb/AIAnalysisPanel_8cpp.html", "d4/deb/AIAnalysisPanel_8cpp" ],
    [ "AIAnalysisPanel.hpp", "d8/df0/AIAnalysisPanel_8hpp.html", "d8/df0/AIAnalysisPanel_8hpp" ],
    [ "AIChatPanel.cpp", "d0/dd3/AIChatPanel_8cpp.html", "d0/dd3/AIChatPanel_8cpp" ],
    [ "AIChatPanel.hpp", "df/dd0/AIChatPanel_8hpp.html", "df/dd0/AIChatPanel_8hpp" ],
    [ "AIConfigPanel.cpp", "d6/d82/AIConfigPanel_8cpp.html", "d6/d82/AIConfigPanel_8cpp" ],
    [ "AIConfigPanel.hpp", "d3/d04/AIConfigPanel_8hpp.html", "d3/d04/AIConfigPanel_8hpp" ],
    [ "AIProviderPlugin.cpp", "d1/d12/AIProviderPlugin_8cpp.html", "d1/d12/AIProviderPlugin_8cpp" ],
    [ "AIProviderPlugin.hpp", "d5/d63/AIProviderPlugin_8hpp.html", "d5/d63/AIProviderPlugin_8hpp" ],
    [ "AIServiceFactory.cpp", "de/d57/AIServiceFactory_8cpp.html", "de/d57/AIServiceFactory_8cpp" ],
    [ "AIServiceFactory.hpp", "d7/db5/AIServiceFactory_8hpp.html", "d7/db5/AIServiceFactory_8hpp" ],
    [ "AnthropicClient.cpp", "db/d8f/AnthropicClient_8cpp.html", "db/d8f/AnthropicClient_8cpp" ],
    [ "AnthropicClient.hpp", "dc/dbf/AnthropicClient_8hpp.html", "dc/dbf/AnthropicClient_8hpp" ],
    [ "Config.hpp", "d8/d2e/plugins_2ai_2Config_8hpp.html", "d8/d2e/plugins_2ai_2Config_8hpp" ],
    [ "GeminiClient.cpp", "dd/d88/GeminiClient_8cpp.html", "dd/d88/GeminiClient_8cpp" ],
    [ "GeminiClient.hpp", "db/dff/GeminiClient_8hpp.html", "db/dff/GeminiClient_8hpp" ],
    [ "IAIService.hpp", "d6/da2/IAIService_8hpp.html", "d6/da2/IAIService_8hpp" ],
    [ "LLMClient.cpp", "db/d61/LLMClient_8cpp.html", "db/d61/LLMClient_8cpp" ],
    [ "LLMClient.hpp", "d3/d14/LLMClient_8hpp.html", "d3/d14/LLMClient_8hpp" ],
    [ "LogAnalyzer.cpp", "de/dda/LogAnalyzer_8cpp.html", "de/dda/LogAnalyzer_8cpp" ],
    [ "LogAnalyzer.hpp", "dc/d47/LogAnalyzer_8hpp.html", "dc/d47/LogAnalyzer_8hpp" ],
    [ "OllamaClient.cpp", "da/d61/OllamaClient_8cpp.html", "da/d61/OllamaClient_8cpp" ],
    [ "OllamaClient.hpp", "d8/d85/OllamaClient_8hpp.html", "d8/d85/OllamaClient_8hpp" ],
    [ "OllamaSetupDialog.cpp", "d4/d4e/OllamaSetupDialog_8cpp.html", null ],
    [ "OllamaSetupDialog.hpp", "da/d1d/OllamaSetupDialog_8hpp.html", "da/d1d/OllamaSetupDialog_8hpp" ],
    [ "OpenAIClient.cpp", "de/dae/OpenAIClient_8cpp.html", "de/dae/OpenAIClient_8cpp" ],
    [ "OpenAIClient.hpp", "d5/d68/OpenAIClient_8hpp.html", "d5/d68/OpenAIClient_8hpp" ]
];