var dir_c3d382106f44a2c7de54a61a6e81f45c =
[
    [ "ConfigEditorDialog.cpp", "df/de3/ConfigEditorDialog_8cpp.html", null ],
    [ "ConfigEditorDialog.hpp", "df/d56/ConfigEditorDialog_8hpp.html", "df/d56/ConfigEditorDialog_8hpp" ],
    [ "ExportDialog.cpp", "da/d3c/ExportDialog_8cpp.html", "da/d3c/ExportDialog_8cpp" ],
    [ "ExportDialog.hpp", "de/d60/ExportDialog_8hpp.html", "de/d60/ExportDialog_8hpp" ],
    [ "FilterEditorDialog.cpp", "d7/daa/FilterEditorDialog_8cpp.html", "d7/daa/FilterEditorDialog_8cpp" ],
    [ "FilterEditorDialog.hpp", "d3/d69/FilterEditorDialog_8hpp.html", "d3/d69/FilterEditorDialog_8hpp" ],
    [ "GemmaDownloadDialog.cpp", "d8/db6/GemmaDownloadDialog_8cpp.html", null ],
    [ "GemmaDownloadDialog.hpp", "d8/dd2/GemmaDownloadDialog_8hpp.html", "d8/dd2/GemmaDownloadDialog_8hpp" ],
    [ "LogFileLoadDialog.cpp", "dc/d57/LogFileLoadDialog_8cpp.html", null ],
    [ "LogFileLoadDialog.hpp", "d2/de5/LogFileLoadDialog_8hpp.html", "d2/de5/LogFileLoadDialog_8hpp" ],
    [ "PluginManagerDialog.cpp", "d0/d6e/PluginManagerDialog_8cpp.html", "d0/d6e/PluginManagerDialog_8cpp" ],
    [ "PluginManagerDialog.hpp", "dd/d2a/PluginManagerDialog_8hpp.html", "dd/d2a/PluginManagerDialog_8hpp" ],
    [ "PreferencesDialog.cpp", "de/d88/PreferencesDialog_8cpp.html", "de/d88/PreferencesDialog_8cpp" ],
    [ "PreferencesDialog.hpp", "d2/d3b/PreferencesDialog_8hpp.html", "d2/d3b/PreferencesDialog_8hpp" ],
    [ "ShortcutsDialog.cpp", "d6/d7d/ShortcutsDialog_8cpp.html", null ],
    [ "ShortcutsDialog.hpp", "db/df6/ShortcutsDialog_8hpp.html", "db/df6/ShortcutsDialog_8hpp" ],
    [ "StructuredConfigDialog.cpp", "d8/d1a/StructuredConfigDialog_8cpp.html", null ],
    [ "StructuredConfigDialog.hpp", "da/dcc/StructuredConfigDialog_8hpp.html", "da/dcc/StructuredConfigDialog_8hpp" ],
    [ "ThemeCustomizationDialog.cpp", "d0/d26/ThemeCustomizationDialog_8cpp.html", null ],
    [ "ThemeCustomizationDialog.hpp", "d8/d2c/ThemeCustomizationDialog_8hpp.html", "d8/d2c/ThemeCustomizationDialog_8hpp" ],
    [ "UpdateDialog.cpp", "d5/d7f/UpdateDialog_8cpp.html", null ],
    [ "UpdateDialog.hpp", "d9/d22/UpdateDialog_8hpp.html", "d9/d22/UpdateDialog_8hpp" ]
];