#include "EvlogParser.hpp"

#include "Error.hpp"
#include "LogEvent.hpp"
#include "Logger.hpp"
#include "Result.hpp"

#include <cstring>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

namespace parser {

// ---------------------------------------------------------------------------
// Fixed header layout
//
// The posix_log_entry struct as generated by evlogd on 32-bit little-endian
// Linux.  All integral fields are stored in native (little-endian) byte order.
// On 32-bit Linux: size_t=4, struct timespec=(4+4), pthread_t=4 → 60 bytes.
// ---------------------------------------------------------------------------

static constexpr size_t   kHdrSize      = 60;
static constexpr size_t   kProgressBatch = 512;

// Byte offsets within the fixed header.
static constexpr size_t kOff_recid      =  0;  // uint32
static constexpr size_t kOff_size       =  4;  // uint32  (payload bytes)
static constexpr size_t kOff_format     =  8;  // int32
static constexpr size_t kOff_event_type = 12;  // uint32
static constexpr size_t kOff_facility   = 16;  // int32
static constexpr size_t kOff_severity   = 20;  // int32
static constexpr size_t kOff_uid        = 24;  // uint32
static constexpr size_t kOff_gid        = 28;  // uint32
static constexpr size_t kOff_pid        = 32;  // int32
static constexpr size_t kOff_tv_sec     = 40;  // int32
static constexpr size_t kOff_tv_nsec    = 44;  // int32
static constexpr size_t kOff_flags      = 48;  // uint32
static constexpr size_t kOff_processor  = 56;  // int32

// log_flags bit masks
static constexpr uint32_t F_TRUNCATE    = 0x01; // POSIX_LOG_TRUNCATE
static constexpr uint32_t F_KERNEL      = 0x02; // EVL_KERNEL_EVENT
static constexpr uint32_t F_BOOT        = 0x04; // EVL_INITIAL_BOOT_EVENT
static constexpr uint32_t F_KERNTIME    = 0x08; // EVL_KERNTIME_LOCAL
static constexpr uint32_t F_INTERRUPT   = 0x10; // EVL_INTERRUPT
static constexpr uint32_t F_PRINTK      = 0x20; // EVL_PRINTK_MESSAGE

// Sanity limits — reject records that exceed these to avoid misparse.
static constexpr uint32_t kMaxPayload   = 64 * 1024; // 64 KB
static constexpr int32_t  kMaxSeverity  = 7;

// ---------------------------------------------------------------------------
// Decode helpers
// ---------------------------------------------------------------------------

static uint16_t LE16u(const uint8_t* p) noexcept
{
    return uint16_t(p[0]) | uint16_t(uint16_t(p[1]) << 8);
}

static uint32_t LE32u(const uint8_t* p) noexcept
{
    return uint32_t{p[0]} | (uint32_t{p[1]} << 8)
         | (uint32_t{p[2]} << 16) | (uint32_t{p[3]} << 24);
}

static int32_t LE32s(const uint8_t* p) noexcept
{
    return static_cast<int32_t>(LE32u(p));
}

static uint64_t LE64u(const uint8_t* p) noexcept
{
    return uint64_t{LE32u(p)} | (uint64_t{LE32u(p + 4)} << 32);
}

// ---------------------------------------------------------------------------

static const char* SeverityName(int32_t s) noexcept
{
    switch (s) {
        case 0: return "Emergency";
        case 1: return "Alert";
        case 2: return "Critical";
        case 3: return "Error";
        case 4: return "Warning";
        case 5: return "Notice";
        case 6: return "Info";
        case 7: return "Debug";
        default: return "Unknown";
    }
}

// Syslog facility codes are stored as the shifted value (e.g. LOG_USER = 8).
static const char* FacilityName(int32_t fac) noexcept
{
    switch (fac) {
        case  0: return "kern";
        case  8: return "user";
        case 16: return "mail";
        case 24: return "daemon";
        case 32: return "auth";
        case 40: return "syslog";
        case 48: return "lpr";
        case 56: return "news";
        case 64: return "uucp";
        case 72: return "cron";
        case 80: return "authpriv";
        case 88: return "ftp";
        case 128: return "local0";
        case 136: return "local1";
        case 144: return "local2";
        case 152: return "local3";
        case 160: return "local4";
        case 168: return "local5";
        case 176: return "local6";
        case 184: return "local7";
        default:  return "unknown";
    }
}

static std::string FlagsString(uint32_t flags)
{
    if (flags == 0) return {};
    std::string s;
    auto append = [&](const char* name) {
        if (!s.empty()) s += ',';
        s += name;
    };
    if (flags & F_TRUNCATE)  append("truncated");
    if (flags & F_KERNEL)    append("kernel");
    if (flags & F_BOOT)      append("boot");
    if (flags & F_KERNTIME)  append("kerntime_local");
    if (flags & F_INTERRUPT) append("interrupt");
    if (flags & F_PRINTK)    append("printk");
    return s;
}

static std::string HexDump(const uint8_t* data, size_t size, size_t maxBytes = 32)
{
    const size_t n = std::min(size, maxBytes);
    std::string s;
    s.reserve(n * 3);
    char buf[4];
    for (size_t i = 0; i < n; ++i) {
        if (i) s += ' ';
        std::snprintf(buf, sizeof(buf), "%02X", data[i]);
        s += buf;
    }
    if (size > maxBytes) s += " ...";
    return s;
}

// ---------------------------------------------------------------------------
// Template-based binary payload decoder
// ---------------------------------------------------------------------------

static std::string DecodeWithTemplate(const uint8_t* data, uint32_t size,
    const EvlogTemplate& tmpl)
{
    std::unordered_map<std::string, std::string> values;
    values.reserve(tmpl.fields.size());
    size_t offset = 0;

    for (const auto& field : tmpl.fields) {
        if (offset >= size) break;

        std::string val;
        switch (field.type) {
            case EvlogTemplateField::Type::Int8:
                val = std::to_string(static_cast<int8_t>(data[offset]));
                offset += 1;
                break;
            case EvlogTemplateField::Type::UInt8:
                val = std::to_string(data[offset]);
                offset += 1;
                break;
            case EvlogTemplateField::Type::Int16:
                val = std::to_string(static_cast<int16_t>(LE16u(data + offset)));
                offset += 2;
                break;
            case EvlogTemplateField::Type::UInt16:
                val = std::to_string(LE16u(data + offset));
                offset += 2;
                break;
            case EvlogTemplateField::Type::Int32:
                val = std::to_string(LE32s(data + offset));
                offset += 4;
                break;
            case EvlogTemplateField::Type::UInt32:
                val = std::to_string(LE32u(data + offset));
                offset += 4;
                break;
            case EvlogTemplateField::Type::Int64:
                val = std::to_string(static_cast<int64_t>(LE64u(data + offset)));
                offset += 8;
                break;
            case EvlogTemplateField::Type::UInt64:
                val = std::to_string(LE64u(data + offset));
                offset += 8;
                break;
            case EvlogTemplateField::Type::Float: {
                float f; std::memcpy(&f, data + offset, 4);
                char buf[32]; std::snprintf(buf, sizeof(buf), "%g", static_cast<double>(f));
                val = buf; offset += 4;
                break;
            }
            case EvlogTemplateField::Type::Double: {
                double d; std::memcpy(&d, data + offset, 8);
                char buf[32]; std::snprintf(buf, sizeof(buf), "%g", d);
                val = buf; offset += 8;
                break;
            }
            case EvlogTemplateField::Type::String: {
                // Fixed-size char buffer: read fixedSize bytes, trim trailing nulls.
                const size_t n = std::min(field.fixedSize, size - offset);
                const char* s = reinterpret_cast<const char*>(data + offset);
                size_t len = ::strnlen(s, n);
                val = std::string(s, len);
                offset += field.fixedSize;
                break;
            }
            case EvlogTemplateField::Type::CString: {
                const char* s = reinterpret_cast<const char*>(data + offset);
                size_t len = ::strnlen(s, size - offset);
                val = std::string(s, len);
                offset += len + 1;
                break;
            }
        }
        values.emplace(field.name, std::move(val));
    }

    // Apply format string: replace %fieldname% placeholders.
    if (!tmpl.formatStr.empty()) {
        std::string result = tmpl.formatStr;
        for (const auto& field : tmpl.fields) {
            auto it = values.find(field.name);
            if (it == values.end()) continue;
            const std::string placeholder = '%' + field.name + '%';
            size_t pos = 0;
            while ((pos = result.find(placeholder, pos)) != std::string::npos) {
                result.replace(pos, placeholder.size(), it->second);
                pos += it->second.size();
            }
        }
        return result;
    }

    // No format string: emit "name=value" pairs in declaration order.
    std::string result;
    for (const auto& field : tmpl.fields) {
        auto it = values.find(field.name);
        if (it == values.end()) continue;
        if (!result.empty()) result += ' ';
        result += field.name + '=' + it->second;
    }
    return result;
}

// ---------------------------------------------------------------------------
// Payload decoders
// ---------------------------------------------------------------------------

static std::string DecodeString(const uint8_t* data, uint32_t size)
{
    if (size == 0) return {};
    // Trim null terminator if present.
    uint32_t len = size;
    while (len > 0 && data[len - 1] == '\0') --len;
    return {reinterpret_cast<const char*>(data), len};
}

// POSIX_LOG_PRINTF: null-terminated format string followed by binary varargs.
// We extract and return the format string; the raw args are appended as hex.
static std::string DecodePrintf(const uint8_t* data, uint32_t size)
{
    if (size == 0) return {};

    // The format string is null-terminated at the start of the payload.
    const char* fmt = reinterpret_cast<const char*>(data);
    const size_t fmtLen = ::strnlen(fmt, size);
    std::string result(fmt, fmtLen);

    // If there are varargs bytes after the null terminator, show them as hex.
    const size_t argsOffset = fmtLen + 1; // skip null
    if (argsOffset < size)
    {
        result += "  [args: ";
        result += HexDump(data + argsOffset, size - argsOffset);
        result += ']';
    }
    return result;
}

// ---------------------------------------------------------------------------
// Template registry setup
// ---------------------------------------------------------------------------

util::Result<void, error::Error> EvlogParser::SetTemplateDirectory(const std::filesystem::path& dir)
{
    util::Logger::Info("[EvlogParser] loading templates from directory: {}", dir.string());
    if (!m_registry) m_registry = std::make_unique<EvlogTemplateRegistry>();
    const size_t before = m_registry->Count();
    auto dirResult = m_registry->LoadFromDirectory(dir);
    if (dirResult.isErr()) {
        util::Logger::Warn("[EvlogParser] LoadFromDirectory failed: {}", dirResult.error().what());
        return dirResult;
    }
    util::Logger::Debug("[EvlogParser] templates loaded from directory: {} new, {} total in registry",
        m_registry->Count() - before, m_registry->Count());
    return util::Result<void, error::Error>::Ok();
}

void EvlogParser::SetTemplateFile(const std::filesystem::path& path)
{
    util::Logger::Debug("[EvlogParser] loading template file: {}", path.string());
    if (!m_registry) m_registry = std::make_unique<EvlogTemplateRegistry>();
    auto fileResult = m_registry->LoadFromFile(path);
    if (fileResult.isErr())
        util::Logger::Warn("[EvlogParser] LoadFromFile failed: {}", fileResult.error().what());
}

// ---------------------------------------------------------------------------
// ParseData entry points
// ---------------------------------------------------------------------------

void EvlogParser::ParseData(const std::filesystem::path& filepath)
{
    util::Logger::Debug("[EvlogParser] opening file: {}", filepath.string());

    std::ifstream file(filepath, std::ios::binary);
    if (!file)
    {
        util::Logger::Error("[EvlogParser] cannot open file: {}", filepath.string());
        throw std::runtime_error("EvlogParser: cannot open: " + filepath.string());
    }

    std::error_code ec;
    const auto fsz = std::filesystem::file_size(filepath, ec);
    m_totalProgress   = (!ec && fsz <= UINT32_MAX) ? static_cast<uint32_t>(fsz) : 0;
    m_currentProgress = 0;
    m_eventId         = 0;

    auto result = ParseStream(file);
    if (result.isErr())
        util::Logger::Warn("[EvlogParser] ParseStream returned error: {}", result.error().what());
}

void EvlogParser::ParseData(std::istream& input)
{
    util::Logger::Debug("[EvlogParser] parsing from stream");
    m_totalProgress   = 0;
    m_currentProgress = 0;
    m_eventId         = 0;
    auto result = ParseStream(input);
    if (result.isErr())
        util::Logger::Warn("[EvlogParser] ParseStream returned error: {}", result.error().what());
}

// ---------------------------------------------------------------------------
// Core streaming loop
// ---------------------------------------------------------------------------

util::Result<int, error::Error> EvlogParser::ParseStream(std::istream& input)
{
    using EventItems = db::LogEvent::EventItems;
    using R = util::Result<int, error::Error>;

    std::vector<std::pair<int, EventItems>> batch;
    batch.reserve(kProgressBatch);

    uint8_t hdr[kHdrSize];
    std::vector<uint8_t> payload;
    uint32_t skipped = 0;

    while (input.good())
    {
        // ── Read fixed header ────────────────────────────────────────────
        input.read(reinterpret_cast<char*>(hdr), kHdrSize);
        const auto gotHdr = static_cast<size_t>(input.gcount());
        m_currentProgress += static_cast<uint32_t>(gotHdr);

        if (gotHdr == 0) break;       // clean EOF
        if (gotHdr < kHdrSize) break; // truncated at end of file

        // ── Decode fixed fields ──────────────────────────────────────────
        const uint32_t recid      = LE32u(hdr + kOff_recid);
        const uint32_t paySize    = LE32u(hdr + kOff_size);
        const int32_t  format     = LE32s(hdr + kOff_format);
        const uint32_t eventType  = LE32u(hdr + kOff_event_type);
        const int32_t  facility   = LE32s(hdr + kOff_facility);
        const int32_t  severity   = LE32s(hdr + kOff_severity);
        const uint32_t uid        = LE32u(hdr + kOff_uid);
        const uint32_t gid        = LE32u(hdr + kOff_gid);
        const int32_t  pid        = LE32s(hdr + kOff_pid);
        const int32_t  tv_sec     = LE32s(hdr + kOff_tv_sec);
        const int32_t  tv_nsec    = LE32s(hdr + kOff_tv_nsec);
        const uint32_t flags      = LE32u(hdr + kOff_flags);
        const int32_t  processor  = LE32s(hdr + kOff_processor);

        // ── Sanity check — skip corrupt records ──────────────────────────
        if (paySize > kMaxPayload
            || severity < 0 || severity > kMaxSeverity
            || format < NODATA || format > PRINTF)
        {
            ++skipped;
            if (skipped <= 10)
                util::Logger::Warn("[EvlogParser] skipping suspect record: "
                    "recid={} size={} fmt={} sev={}",
                    recid, paySize, format, severity);
            // Without knowing the real record size we cannot safely skip
            // past just this one record, so abort the stream.
            break;
        }

        // ── Warn on unrecognised facility ────────────────────────────────
        if (std::string_view{FacilityName(facility)} == "unknown")
            util::Logger::Warn("[EvlogParser] unknown facility code {} in recid={}", facility, recid);

        // ── Per-record trace ─────────────────────────────────────────────
        util::Logger::Trace("[EvlogParser] record #{}: recid={} sev={} fac={} fmt={} paySize={}",
            m_eventId, recid, SeverityName(severity), FacilityName(facility), format, paySize);

        // ── Read variable payload ─────────────────────────────────────────
        if (paySize > 0)
        {
            payload.resize(paySize);
            input.read(reinterpret_cast<char*>(payload.data()),
                       static_cast<std::streamsize>(paySize));
            const auto gotPay = static_cast<uint32_t>(input.gcount());
            m_currentProgress += gotPay;
            if (gotPay < paySize) break; // truncated record at EOF
        }

        // ── Decode payload to info string ─────────────────────────────────
        std::string info;
        switch (static_cast<Format>(format))
        {
            case NODATA:
                break;
            case STRING:
                info = DecodeString(payload.data(), paySize);
                break;
            case PRINTF:
                info = DecodePrintf(payload.data(), paySize);
                break;
            case BINARY: {
                const EvlogTemplate* tmpl = m_registry
                    ? m_registry->Find(facility, eventType)
                    : nullptr;
                if (tmpl)
                {
                    info = DecodeWithTemplate(payload.data(), paySize, *tmpl);
                }
                else
                {
                    if (paySize > 0)
                        util::Logger::Warn("[EvlogParser] no template for facility={} "
                            "event_type=0x{:08X} in recid={} — emitting hex dump",
                            facility, eventType, recid);
                    info = HexDump(payload.data(), paySize);
                }
                break;
            }
        }

        // ── Build timestamp string ────────────────────────────────────────
        char tsBuf[32];
        const double ts = static_cast<double>(tv_sec)
                        + static_cast<double>(tv_nsec) / 1e9;
        std::snprintf(tsBuf, sizeof(tsBuf), "%.9f", ts);

        // ── Assemble event items ──────────────────────────────────────────
        EventItems items;
        items.reserve(12);

        items.emplace_back("timestamp",  tsBuf);
        items.emplace_back("level",      SeverityName(severity));
        items.emplace_back("facility",   FacilityName(facility));

        char typeBuf[12];
        std::snprintf(typeBuf, sizeof(typeBuf), "0x%08X", eventType);
        items.emplace_back("event_type", typeBuf);

        char pidBuf[12];
        std::snprintf(pidBuf, sizeof(pidBuf), "%d", pid);
        items.emplace_back("pid", pidBuf);

        char uidBuf[12];
        std::snprintf(uidBuf, sizeof(uidBuf), "%u", uid);
        items.emplace_back("uid", uidBuf);

        char gidBuf[12];
        std::snprintf(gidBuf, sizeof(gidBuf), "%u", gid);
        items.emplace_back("gid", gidBuf);

        char recBuf[12];
        std::snprintf(recBuf, sizeof(recBuf), "%u", recid);
        items.emplace_back("recid", recBuf);

        if (processor != 0)
        {
            char cpuBuf[8];
            std::snprintf(cpuBuf, sizeof(cpuBuf), "%d", processor);
            items.emplace_back("cpu", cpuBuf);
        }

        const std::string flagStr = FlagsString(flags);
        if (!flagStr.empty())
            items.emplace_back("flags", flagStr);

        if (!info.empty())
            items.emplace_back("info", std::move(info));

        batch.emplace_back(m_eventId++, std::move(items));

        if (batch.size() >= kProgressBatch)
        {
            NotifyNewEventBatch(std::move(batch));
            NotifyProgressUpdated();
            batch.clear();
            batch.reserve(kProgressBatch);
        }
    }

    if (!batch.empty())
    {
        NotifyNewEventBatch(std::move(batch));
        NotifyProgressUpdated();
    }

    if (skipped > 0)
        util::Logger::Warn("[EvlogParser] {} suspect record(s) caused early stop — "
            "file may be from a 64-bit evlogd build (header size mismatch)", skipped);

    util::Logger::Info("[EvlogParser] parse complete: {} record(s) emitted", m_eventId);
    return R::Ok(m_eventId);
}

} // namespace parser
