# Enable sanitizers if supported (excluding Windows)
if (NOT WIN32 AND (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU"))
    option(ENABLE_SANITIZERS "Enable Address and Undefined Behavior Sanitizers" ON)
    if (ENABLE_SANITIZERS)
        message(STATUS "Enabling sanitizers")
        target_compile_options(${PROJECT_NAME} PRIVATE -fsanitize=address,undefined)
        target_link_options(${PROJECT_NAME} PRIVATE -fsanitize=address,undefined)
    endif()
else()
    message(STATUS "Sanitizers are disabled on Windows.")
endif()