name: macOS CI (clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    env:
      BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_GENERATOR: Ninja
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      GTEST_COLOR: 1

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Homebrew)
        run: |
          brew update
          brew install ninja ccache wxwidgets expat cppcheck

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-macos-clang-${{ matrix.build_type }}-${{ github.sha }}
          restore-keys: |
            ccache-macos-clang-${{ matrix.build_type }}-
            ccache-macos-clang-

      - name: Toolchain info
        run: |
          which clang++
          clang++ --version
          wx-config --version

      - name: Configure
        run: |
          cmake -B "$BUILD_DIR" -S "$GITHUB_WORKSPACE" \
            -G "$CMAKE_GENERATOR" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }}

      - name: Static analysis (cppcheck)
        if: matrix.build_type == 'Debug'
        run: |
          cppcheck --enable=warning,performance,portability \
                   --inline-suppr --error-exitcode=1 \
                   -I src -I include \
                   src 2> cppcheck-report.txt || (cat cppcheck-report.txt; exit 1)
          cat cppcheck-report.txt

      - name: List tests
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -N || true

      - name: Run tests
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -j"$(sysctl -n hw.logicalcpu)" --build-config ${{ matrix.build_type }} --output-on-failure

      - name: Install (staging)
        if: matrix.build_type == 'Release'
        run: |
          cmake --install "$BUILD_DIR" --config Release --prefix "$BUILD_DIR/_staging"

      - name: Verify CPack config
        if: matrix.build_type == 'Release' && github.ref == 'refs/heads/main'
        run: test -f "$BUILD_DIR/CPackConfig.cmake"

      - name: Package (CPack DMG)
        if: matrix.build_type == 'Release' && github.ref == 'refs/heads/main'
        working-directory: ${{ env.BUILD_DIR }}
        run: cpack -G DragNDrop -C Release --config CPackConfig.cmake

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.build_type }}-artifacts
          path: |
            ${{ env.BUILD_DIR }}/_staging/**
            ${{ env.BUILD_DIR }}/_CPack_Packages/*/DragNDrop/*.dmg
            ${{ env.BUILD_DIR }}/Testing/Temporary/LastTest.log
          if-no-files-found: ignore
