name: CMake on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang mingw-w64-x86_64-wxwidgets3.2-msw

      - name: Configuring
        run: |
          clang --version
          cmake --version
          mkdir build_cmake
          pushd build_cmake
          cmake -G "MinGW Makefiles" \
                -DCMAKE_C_COMPILER=clang.exe \
                -DCMAKE_CXX_COMPILER=clang++.exe \
                -DCMAKE_BUILD_TYPE=Release \
                ..

      - name: Building
        working-directory: build_cmake
        run: |
          cmake --build . -- -j

      - name: Test
        shell: cmd
        working-directory: build_cmake
        run: ctest --build-config Release

      - name: Cpack
        working-directory: build_cmake
        run: |
          cpack -G ZIP

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LogViewer_mvsc
          path: dist/packages
