name: CMake on Windows (MSYS2 MinGW)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    env:
      BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_GENERATOR: Ninja
      CCACHE_DIR: ${{ github.workspace }}\\.ccache
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      GTEST_COLOR: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-ccache
            mingw-w64-x86_64-wxWidgets3.2
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-gtest

      - name: Show toolchain
        shell: msys2 {0}
        run: |
          echo "PATH=$PATH"
          which gcc || true
          which g++ || true
          which ninja || true
          which wx-config || true
          wx-config --version || true

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-mingw-${{ matrix.build_type }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-mingw-${{ matrix.build_type }}-
            ccache-${{ runner.os }}-mingw-

      - name: Configure CMake (MinGW64)
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"
          cmake -B "$BUILD_DIR" -S "$GITHUB_WORKSPACE" \
                -G "$CMAKE_GENERATOR" \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_C_COMPILER=/mingw64/bin/gcc \
                -DCMAKE_CXX_COMPILER=/mingw64/bin/g++ \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        shell: msys2 {0}
        run: cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }}

      - name: List tests
        shell: msys2 {0}
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -N || true

      - name: Test
        shell: msys2 {0}
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -j"$(nproc)" --build-config ${{ matrix.build_type }} --output-on-failure

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-logs-windows-${{ matrix.build_type }}
          path: |
            ${{ env.BUILD_DIR }}/Testing/Temporary/LastTest.log
            ${{ env.BUILD_DIR }}/Testing/**/Test.xml
            ${{ env.BUILD_DIR }}/CTestTestfile.cmake
