name: CMake on macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    env:
      BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_GENERATOR: Ninja
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      GTEST_COLOR: 1

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Homebrew)
        run: |
          brew update
          brew install ninja ccache wxwidgets expat

      - name: Show toolchain
        run: |
          echo "PATH=$PATH"
          which clang || true
          which clang++ || true
          clang++ --version || true
          which wx-config || true
          wx-config --version || true

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-clang-${{ matrix.build_type }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-clang-${{ matrix.build_type }}-
            ccache-${{ runner.os }}-clang-

      - name: Configure CMake
        run: |
          # Ensure brew is early in PATH, but keep the system PATH (contains /usr/bin/clang++)
          export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
          cmake -B "${BUILD_DIR}" -S "${{ github.workspace }}" \
                -G "${CMAKE_GENERATOR}" \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_C_COMPILER="$(command -v clang)" \
                -DCMAKE_CXX_COMPILER="$(command -v clang++)" \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build "${BUILD_DIR}" --config ${{ matrix.build_type }}

      - name: List tests
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -N || true

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -j"$(sysctl -n hw.logicalcpu)" --build-config ${{ matrix.build_type }} --output-on-failure

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-logs-macos-${{ matrix.build_type }}
          path: |
            ${{ env.BUILD_DIR }}/Testing/Temporary/LastTest.log
            ${{ env.BUILD_DIR }}/Testing/**/Test.xml
            ${{ env.BUILD_DIR }}/CTestTestfile.cmake
