name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        cpp_compiler: [g++, clang++]

    env:
      BUILD_DIR: ${{ github.workspace }}/build
      CMAKE_GENERATOR: Ninja
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build ccache \
            libgtk-3-dev libwxgtk3.2-dev libexpat1-dev \
            g++ clang

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ matrix.cpp_compiler }}-${{ matrix.build_type }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.cpp_compiler }}-${{ matrix.build_type }}-
            ccache-${{ runner.os }}-${{ matrix.cpp_compiler }}-

      - name: Configure CMake
        run: |
          cmake -B "${BUILD_DIR}" -S "${{ github.workspace }}" \
                -G "${CMAKE_GENERATOR}" \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build "${BUILD_DIR}" --config ${{ matrix.build_type }}

      - name: List tests
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -N || true

      - name: Test (headless with Xvfb)
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          # Run tests under a virtual X server to satisfy any wx GUI needs
          xvfb-run -a ctest -j"$(nproc)" --build-config ${{ matrix.build_type }} \
                   --output-on-failure --rerun-failed

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-logs-${{ matrix.cpp_compiler }}-${{ matrix.build_type }}
          path: |
            ${{ env.BUILD_DIR }}/Testing/Temporary/LastTest.log
            ${{ env.BUILD_DIR }}/Testing/**/Test.xml
            ${{ env.BUILD_DIR }}/CTestTestfile.cmake
